name: Frontend & Backend Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install frontend dependencies
        working-directory: dj
        run: npm ci
      - name: Build frontend
        working-directory: dj
        run: npm run build
      - name: Lint frontend
        working-directory: dj
        run: npm run lint
      - name: Install backend dependencies
        working-directory: server
        run: npm ci
